### ISSUE TITLE
COT with booleans fails to coerce into bool

### ISSUE THREAD

**Issue by aaronvg** [BoundaryML/baml#860] opened 2024-08-05 22:03 UTC
https://www.promptfiddle.com/New-Project-GSO_w

**Comment by eugene-yaroslavtsev** [comment] 2024-10-16 14:36
Looks like this is still an issue:

Example unhandled output:

```
False. 

The statement "2 + 2 = 5" is mathematically incorrect. The correct sum of 2 + 2 is 4, not 5.
```

For contrast, this output is correctly handled:

```
false

The statement 2 + 2 = 5 is mathematically incorrect. The correct sum of 2 + 2 is 4.
```

I haven't had a chance to look at the internals of the codebase, but my speculative suspicion is this might be an edge case for when the output is a primitive?

Just wanted to share a concrete example of @aaronvg's issue first before diving in to check under the hood.

**Comment by hellovai** [comment] 2024-10-16 14:39
yep! We have a patch for this going out in this weeks release! we already did the work to support literal types and are just using that again for booleans!

For example:

```
function PickCategory(message: string) -> "spam" | "sales" | "product" {
  ...
}
```

will now correctly pick from there even if there's supporting text

**Comment by eugene-yaroslavtsev** [comment] 2024-10-16 14:44
Thanks for the quick response @hellovai! Unfortunately, to make matters worse, I just noticed this disastrous case:

> False. The statement "2 + 2 = 5" is not accurate according to basic arithmetic. In standard arithmetic, the sum of 2 and 2 is equal to 4, not 5. Therefore, the statement does not hold true.

This gets coerced to `true`. Does your guys' patch address a case like this?

Naturally, the author's prompt isn't great in this case (it should ask for the model to perform CoT *before* answering), but people are gonna do that in the real world. I started looking at the code base to try to understand where the issue is, would you be so kind as to link me to the PR where you guys fix this? 

BAML is the first project of this kind I've taken seriously since `instructor` due to the fact that it's so lightweight and well-designed; so I'd love to contribute back where I can.

**Comment by aaronvg** [comment] 2024-10-16 15:24
Theres a heuristic here where we could know if the first word is the actual boolean. Otherwise we'd  do best effort and try to grab the last value (or fail if theres ambiguity)

**Comment by antoniosarosi** [comment] 2024-10-18 14:14
> False. The statement "2 + 2 = 5" is not accurate according to basic arithmetic. In standard arithmetic, the sum of 2 and 2 is equal to 4, not 5. Therefore, the statement does not hold true.

This gets coerced to `true` because there's a little bug in the substring match function, the literals patch won't fix it. I'll open another PR for this issue, but this particular case currently should fail because of ambiguity, the answer contains both `false` and `true`. We could just return the first one we encounter and coerce to `false` but then if you flip the statements it won't work:

> The statement does not hold true. The statement "2 + 2 = 5" is not accurate according to basic arithmetic. In standard arithmetic, the sum of 2 and 2 is equal to 4, not 5. Therefore, the statement is false.

This would coerce to `true` if we pick the first option in the string. So not sure if any heuristics could fix this, it looks like we need an LLM to understand the output of an LLM :rofl: . Best solution for now I think is fail with ambiguity.

**Closed as completed** 2024-10-18 15:51 UTC
